[
   Module                   -- V vs=1[H[KW["module"] _1] _2 _3],
   Module.2:iter-star       -- _1,
   Module.3:iter-star       -- _1,
   Entity                   -- V vs=1[V is=2[H[KW["entity"] _1 KW["{"]] _2] KW["}"]],
   Entity.2:iter-star       -- _1,
   Import                   -- H[KW["import"] _1],
   WildcardImport           -- H hs=0[_1 KW["."] KW["*"]],
   EntityImport             -- H hs=0[_1 KW["."] _2],
   Aspect                   -- V is=2[H[KW["aspect"] _1 KW["{"]] _2] KW["}"],
   Aspect.2:iter-star       -- _1,
   Pointcut                 -- V is=2[H[KW["pointcut"] H hs=0[_1 KW["("] _2 KW[")"] KW[":"]]] _3],
   Pointcut.2:iter-star-sep -- H hs=0[_1 KW[", "]],
   Pointcut.3:iter-sep      -- H hs=0[_1 KW[", "]],
   Advice                   -- V is=2[H[KW["advice"] _1 H hs=0[_2 KW["("] _3 KW[")"] KW[": "] _4 KW["("] _5 KW[")"]]] _6],
   Advice.3:iter-star-sep   -- H hs=0[_1 KW[", "]],
   Advice.5:iter-star-sep   -- H hs=0[_1 KW[", "]],
   Before                   -- KW["before"],
   After                    -- KW["after"],
   Assigned                 -- H[KW["assigned"] H hs=0[KW["("] _1 KW[")"]]],
   Property                 -- H[_1 KW[":"] _2],
   Function                 -- H hs=0[_1 KW["("] _2 KW[")"]] _3,
   Function.2:iter-star-sep -- H hs=0[_1 KW[", "]],
   Param                    -- H[_1 KW[":"] _2],
   VarDecl                  -- H[KW["var"] _1 KW[":"] _2],
   VarDeclInit              -- H[KW["var"] _1 KW[":"] _2 KW["="] _3],
   Assign                   -- H[_1 KW["="] _2],
   Block                    -- V is=2 [H[KW["{"]] _1] KW["}"],
   Block.1:iter-star        -- V[_1],
   Print                    -- H[KW["print"] _1],
   Call                     -- H hs=0[_1 KW["("] _2 KW[")"]],
   Call.2:iter-star-sep     -- H hs=0[_1 KW[", "]],
   Var                      -- _1,
   PropAccess               -- H hs=0[_1 KW["."] _2],
   StringLit                -- _1,
   IntLit                   -- _1,
   Type                     -- _1,
   StringType               -- KW["String"],
   IntType                  -- KW["Int"]
]
