[
   Start                   -- _1 _2,
   Start.1:iter-star       -- _1,
   Start.2:iter-star       -- _1,
   Include                 -- KW["include"] KW["\""] _1 KW["\""],
   Include                 -- KW["include"] KW["<"] _1 KW[">"],
   FunDecl                 -- _1 _2 KW["("] _3 KW[")"] KW["{"] _4 KW["}"],
   FunDecl.3:iter-star-sep -- _1 KW[","],
   FunDecl.4:iter-star     -- _1,
   Param                   -- _1 _2,
   TypeDecl                -- _1 KW[";"],
   TypeDef                 -- KW["typedef"] _1 _2,
   TypeDef                 -- KW["typedef"] _1 _2,
   StructDecl              -- KW["struct"] _1 KW["{"] _2 KW["}"],
   StructDecl.2:iter-star  -- _1,
   Field                   -- _1 _2 KW[";"],
   VarDecl                 -- _1 _2 KW[";"],
   Stmt                    -- _1 KW[";"],
   Assign                  -- _1 KW["="] _2 KW[";"],
   Return                  -- KW["return"] _1 KW[";"],
   StrLit                  -- _1,
   IntLit                  -- _1,
   Call                    -- _1 KW["("] _2 KW[")"],
   Call.2:iter-star-sep    -- _1 KW[","],
   SizeOf                  -- KW["sizeof"] KW["("] _1 KW[")"],
   Access                  -- _1 KW["."] _2,
   DerefAccess             -- _1 KW["->"] _2,
   Deref                   -- KW["*"] _1,
   Ref                     -- KW["&"] _1,
   VarRef                  -- _1,
   Cast                    -- KW["("] _1 KW[")"] _2,
   Type                    -- _1,
   Char                    -- KW["char"],
   Int                     -- KW["int"],
   Void                    -- KW["void"],
   Pointer                 -- _1 KW["*"],
   StructRef               -- KW["struct"] _1
]